name: Docker Build

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Environment
        uses: docker/setup-buildx-action@v1
        
      - name: Build Docker image
        run: docker build . -t my-application
        
      - name: Run Docker container
        run: docker run -it --rm my-application