name: Python and C application test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python_tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run tests in lab1
      run: |
        python -m unittest discover -s lab1 -p 'test_*.py'
    - name: Run tests in lab2
      run: |
        python -m unittest discover -s lab2 -p 'test_*.py'
    - name: Run tests in lab3
      run: |
        python -m unittest discover -s lab3 -p 'test_*.py'

  c_tests:
    needs: python_tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install C/C++ compiler and make
      run: sudo apt-get update && sudo apt-get install build-essential
    - name: Build and Run C tests in lab4
      run: |
        cd lab4
        make
        ./test 